# Generated by Django 5.2.8 on 2025-11-30 22:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(default='units', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
