# Generated by Django 5.2.8 on 2025-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('productivity', 'Productivity'), ('learning', 'Learning'), ('mindfulness', 'Mindfulness'), ('social', 'Social')], default='health', max_length=20),
        ),
    ]
